# -- Theme Options --
# 参数名参照 Hextra 文档：https://imfing.github.io/hextra/docs/

[navbar]
  displayTitle = true
  displayLogo = false
  width = "wide"

[theme]
  # light | dark | system
  default = "system"
  displayToggle = true

[footer]
  enable = true
  displayCopyright = true
  displayPoweredBy = true
  width = "normal"

[search]
  enable = true
  type = "flexsearch"

  [search.flexsearch]
    index = "content"
    tokenize = "forward"

[page]
  # full (100%), wide (90rem), normal (80rem)
  width = "normal"

[toc]
  displayTags = false

[highlight]
  copy = { enable = true, display = "hover" }

imageZoom = { enable = true }
